//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGB.Core.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BGB.Core.Validations.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta corrente é obrigatória..
        /// </summary>
        public static string AccountIsRequired {
            get {
                return ResourceManager.GetString("AccountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor tem que ser igual ou maior ao valor mínimo..
        /// </summary>
        public static string AmountGreaterMinimum {
            get {
                return ResourceManager.GetString("AmountGreaterMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor é obrigatório..
        /// </summary>
        public static string AmountIsRequired {
            get {
                return ResourceManager.GetString("AmountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF/CNPJ é obrigatório..
        /// </summary>
        public static string CpfCnpjIsRequired {
            get {
                return ResourceManager.GetString("CpfCnpjIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cpf é inválido..
        /// </summary>
        public static string CpfIsInvalid {
            get {
                return ResourceManager.GetString("CpfIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cpf é obrigatório..
        /// </summary>
        public static string CpfIsRequired {
            get {
                return ResourceManager.GetString("CpfIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credencial de acesso precisa ser informada..
        /// </summary>
        public static string CredentialIsRequired {
            get {
                return ResourceManager.GetString("CredentialIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente precisa ser informado..
        /// </summary>
        public static string CustomerIsRequired {
            get {
                return ResourceManager.GetString("CustomerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não pode ter mais de 100 caracteres..
        /// </summary>
        public static string EmailLengthCanNotGreaterThan100 {
            get {
                return ResourceManager.GetString("EmailLengthCanNotGreaterThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data final precisa ser informada..
        /// </summary>
        public static string EndDateIsRequired {
            get {
                return ResourceManager.GetString("EndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data prevista é inválida..
        /// </summary>
        public static string ExpectedDateIsInvalid {
            get {
                return ResourceManager.GetString("ExpectedDateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de saque é inferior a 3 dias de diferença da data de comunicação..
        /// </summary>
        public static string ExpectedDateOutOfDeadline {
            get {
                return ResourceManager.GetString("ExpectedDateOutOfDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A finalidade é obrigatória..
        /// </summary>
        public static string FinalityIsRequired {
            get {
                return ResourceManager.GetString("FinalityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A finalidade não pode ter mais de 150 caracteres..
        /// </summary>
        public static string FinalityLengthCanNotBeGreaterThan150 {
            get {
                return ResourceManager.GetString("FinalityLengthCanNotBeGreaterThan150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa ser informada..
        /// </summary>
        public static string KeyIsRequired {
            get {
                return ResourceManager.GetString("KeyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login precisa ser informado..
        /// </summary>
        public static string LoginIsRequired {
            get {
                return ResourceManager.GetString("LoginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O loginnão pode ter mais de 30 caracteres..
        /// </summary>
        public static string LoginLengthCanNotGreaterThan30 {
            get {
                return ResourceManager.GetString("LoginLengthCanNotGreaterThan30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ter mais de 50 caracteres..
        /// </summary>
        public static string NameLengthCanNotGreaterThan50 {
            get {
                return ResourceManager.GetString("NameLengthCanNotGreaterThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do sacador é obrigatório..
        /// </summary>
        public static string PayeeNameIsRequired {
            get {
                return ResourceManager.GetString("PayeeNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do sacador não pode ter mais de 100 caracteres..
        /// </summary>
        public static string PayeeNameLengthCanNotBeGreaterThan100 {
            get {
                return ResourceManager.GetString("PayeeNameLengthCanNotBeGreaterThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial precisa ser informada..
        /// </summary>
        public static string StartDateIsRequired {
            get {
                return ResourceManager.GetString("StartDateIsRequired", resourceCulture);
            }
        }
    }
}
